plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

configurations {
    localRuntime
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
        gameTestServer {
            server()
            systemProperty 'neoforge.enableGameTest', 'true'
            systemProperty 'neoforge.gameTestServer', 'true'
            programArguments.addAll '--nogui'
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.register('syncLocalRuntimeMods', Sync) {
    from configurations.localRuntime
    into layout.projectDirectory.dir('run/mods')
}

tasks.matching { it.name.startsWith('run') }.configureEach {
    dependsOn 'syncLocalRuntimeMods'
}
tasks.named('neoForgeIdeSync').configure {
    dependsOn 'syncLocalRuntimeMods'
}

repositories {
    maven {
        name = 'CreateMod'
        url = 'https://maven.createmod.net'
    }
    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'RyanHCode'
                url = 'https://maven.ryanhcode.dev/releases'
            }
        }
        filter {
            includeGroupAndSubgroups('dev.ryanhcode')    // Sable, Offroad
            includeGroupAndSubgroups('dev.eriksonn')     // Aeronautics
            includeGroup('dev.simulated_team.simulated') // Simulated
        }
    }
}

dependencies {
    localRuntime "mezz.jei:jei-1.21.1-neoforge:${jei_neoforge_version}"
    compileOnly("com.simibubi.create:create-1.21.1:${create_neoforge_version}") { transitive = false }
    localRuntime("com.simibubi.create:create-1.21.1:${create_neoforge_version}") { transitive = false }
    localRuntime("dev.simulated_team.simulated:simulated-neoforge-1.21.1:${create_aeronautics_version}") { transitive = false }
    localRuntime("dev.eriksonn.aeronautics:aeronautics-neoforge-1.21.1:${create_aeronautics_version}") { transitive = false }
    localRuntime("dev.ryanhcode.offroad:offroad-neoforge-1.21.1:${create_aeronautics_version}") { transitive = false }
    localRuntime("dev.ryanhcode.sable:sable-neoforge-1.21.1:${sable_version}") { transitive = false }
    localRuntime "curse.maven:cold-sweat-506194:${cold_sweat_cf_file_id}" 
}
